def path = 'Employees.Api\\Employees.Api.sln'

pipeline {
 agent any
 stages {
  stage('Checkout') {
   steps {
    checkout scm
   }
   stage('Checkout') {
   steps {
    sh '''
         dotnet --version
      '''
   }
  }
 }
}